### ISSUE TITLE
Release to Hackage?

### ISSUE THREAD

**Issue by mpilgrem** [mpilgrem/random-dot-org#1]
Hackage already has a package `RandomDotOrg` marked as deprecated, I think for some time (it was last uploaded in 2008), maintained by Austin Seipp, who is known as @thoughtpolice on GitHub. Perhaps it could be re-purposed for this package, as `RandomDotOrg-0.3`?

@thoughtpolice, would you be willing to add me as a maintainer of your existing deprecated package, for that purpose? If so, am am `mpilgrem` on Hackage.

**Comment by mpilgrem** [comment]
@thoughtpolice, sorry to press, but I wondered if you had seen my question to you above and had a chance to consider it? It would be useful to know whether or not you think that is a possibility.

**Comment by thoughtpolice** [comment]
Sorry, I've been quite busy and generally don't operate too much in the Haskell community anymore (though I do use Haskell still.) I've also been reluctant in the past to add too many people to maintainer status on the packages I upload, but in this case it's a low risk package and you seem to have a history of Haskell contributions.

I'll look at trying to add you to the maintainer group sometime soon; maybe this weekend, though if you need it sooner then just let me know.

**Comment by mpilgrem** [comment]
@thoughtpolice, thank you - that is much appreciated.

**Comment by mpilgrem** [comment]
@thoughtpolice, I hope you do not mind if I nudge you on this, as I have some time to spend on it this weekend.

**Comment by thoughtpolice** [comment]
@mpilgrem Done!

**Comment by mpilgrem** [comment]
`RandomDotOrg-1.0` published on Hackage.
